((:source "~/Notes/Program/Tools/Tmux.org" :target "~/Projects/Glorg/content/snippet/tmux.org")
 (:source "~/Notes/Program/Tools/OrgMode.org" :target "~/Projects/Glorg/content/snippet/orgmode.org")
 (:source "~/Notes/Program/Algorithm/Sort.org" :target "~/Projects/Glorg/content/algorithm/sort.org")
 (:source "~/Notes/Program/Linux/ArchLinux.org" :target "~/Projects/Glorg/content/snippet/archlinux.org")
 (:source "~/Notes/Program/Linux/Commands.org" :target "~/Projects/Glorg/content/snippet/commands.org")
 (:source "~/Notes/Program/Lisp/CommonLisp.org" :target "~/Projects/Glorg/content/snippet/commonlisp.org"))
